version: '3.8'

services:
 
  db:
    image: postgres:14-alpine
    container_name: mi_base_de_datos
    environment:
      POSTGRES_USER: admin     
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: socialdb     
    ports:
      - "5432:5432" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 